//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drinago
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sadrzaj
    {
        public int ID { get; set; }
        public string History1 { get; set; }
        public string History2 { get; set; }
    }
}
